"""
Auto-generated trader_optimized.py — IMC Prosperity 4
Generated by train.py v2 on 2026-03-21 12:55:53
Features: Kalman FV, OBI, multi-level quoting, vol-adaptive spread, penny jumping,
          trend following, aggressive taking, adversarial fill prevention,
          pairs trading, lead-lag, basket arb, conversion arb,
          BSM IV mean-reversion, toxic flow detection, circuit breakers
"""
from datamodel import Order, OrderDepth, TradingState, Trade, Listing, Observation, ConversionObservation
import math
from typing import Dict, List, Tuple, Any

PARAMS = {
    "resin_spread": 4,
    "resin_order_qty": 24,
    "resin_skew_factor": 0.8851375156550184,
    "resin_soft_frac": 0.82071573771729,
    "resin_take_width": 0.7508314647068891,
    "resin_penny_jump": 0,
    "kelp_ema_alpha": 0.061902928758832465,
    "kelp_spread": 7,
    "kelp_order_qty": 17,
    "kelp_skew_factor": 0.8524421348242497,
    "kelp_soft_frac": 0.832403055406228,
    "squid_ema_alpha": 0.5462988636232168,
    "squid_spread": 4,
    "squid_order_qty": 14,
    "squid_skew_factor": 0.28312661589656685,
    "squid_soft_frac": 0.7091074407009843,
    "kf_Q": 0.008231607635765654,
    "kf_R": 4.591896420514712,
    "use_kalman_fv": 1,
    "trend_enabled": 0,
    "trend_threshold": 0.00337473170732784,
    "trend_qty": 2,
    "take_enabled": 0,
    "take_edge_min": 3.8166336515322,
    "obi_enabled": 0,
    "obi_weight": 1.5464385462796808,
    "multi_level": 1,
    "multi_level_decay": 0.5491340783908502,
    "vol_adapt_enabled": 1,
    "vol_adapt_scale": 0.5073797372198606,
    "vol_adapt_window": 69,
    "penny_jump_enabled": 0,
    "adverse_vol_limit": 5,
    "lead_lag_enabled": 1,
    "lead_lag_window": 98,
    "pairs_enabled": 1,
    "pairs_z_enter": 3.7741526364966442,
    "pairs_z_exit": 0.1354600333904633,
    "pairs_window": 52,
    "pairs_qty": 1,
    "toxic_flow_enabled": 1,
    "toxic_threshold": 0.8025091462282582,
    "cb_loss_limit": -125.23208012115253,
    "cb_cooldown_ticks": 189,
    "warmup_ticks": 4,
    "liquidation_start": 866,
    "close_start": 986,
    "size_mult_small": 0.44999925058358237,
    "size_mult_half": 0.5950108960389429,
    "basket_z_enter": 0.8547144550894885,
    "basket_z_exit": 1.9671036978778287,
    "basket_window": 95,
    "basket_order_qty": 10,
    "bsm_enabled": 1,
    "bsm_vol_window": 76,
    "bsm_z_enter": 2.8693154975816286,
    "bsm_qty": 4
}
POSITION_LIMITS = {
    "RAINFOREST_RESIN": 50,
    "KELP": 50,
    "SQUID_INK": 50,
    "CROISSANTS": 250,
    "JAMS": 350,
    "DJEMBES": 60,
    "PICNIC_BASKET1": 60,
    "PICNIC_BASKET2": 100,
    "VOLCANIC_ROCK": 400,
    "VOLCANIC_ROCK_VOUCHER_9500": 200,
    "VOLCANIC_ROCK_VOUCHER_9750": 200,
    "VOLCANIC_ROCK_VOUCHER_10000": 200,
    "VOLCANIC_ROCK_VOUCHER_10250": 200,
    "VOLCANIC_ROCK_VOUCHER_10500": 200,
    "MAGNIFICENT_MACARONS": 75
}
STABLE_PRODUCTS = {
    "RAINFOREST_RESIN": 10000.0
}
VOLATILE_PRODUCTS = [
    "KELP",
    "SQUID_INK"
]
BASKET_PRODUCTS = {
    "PICNIC_BASKET1": {
        "CROISSANTS": 6,
        "JAMS": 3,
        "DJEMBES": 1
    },
    "PICNIC_BASKET2": {
        "CROISSANTS": 4,
        "JAMS": 2
    }
}
VOUCHER_STRIKES = {
    "VOLCANIC_ROCK_VOUCHER_9500": 9500,
    "VOLCANIC_ROCK_VOUCHER_9750": 9750,
    "VOLCANIC_ROCK_VOUCHER_10000": 10000,
    "VOLCANIC_ROCK_VOUCHER_10250": 10250,
    "VOLCANIC_ROCK_VOUCHER_10500": 10500
}
TICKS_PER_DAY = 10000


class Trader:
    def __init__(self):
        self.emas = {}
        self.kalman = {}
        self.spread_history = {}
        self.tick = 0
        self.prices = {}
        self.returns = {}
        self.fill_counts = {}
        self.strategy_pnl = {}
        self.cb_disabled_until = {}
        self.lead_lag_cache = {}
        self.iv_history = {}

    def _kalman_update(self, product, z):
        p = PARAMS
        Q, R = p.get("kf_Q", 0.05), p.get("kf_R", 1.0)
        kf = self.kalman.get(product, {"x": None, "P": 1.0})
        x, P = kf["x"], kf["P"]
        if x is None:
            kf["x"], kf["P"] = z, 1.0
            self.kalman[product] = kf
            return z
        P_pred = P + Q
        K = P_pred / (P_pred + R)
        x_new = x + K * (z - x)
        kf["x"], kf["P"] = x_new, (1 - K) * P_pred
        self.kalman[product] = kf
        return x_new

    def _obi(self, od):
        bv = sum(od.buy_orders.values())
        av = sum(abs(v) for v in od.sell_orders.values())
        t = bv + av
        return (bv - av) / t if t > 0 else 0.0

    def _realized_vol(self, product, window=50):
        rets = self.returns.get(product, [])
        if len(rets) < window:
            return 0.0
        r = rets[-window:]
        m = sum(r) / len(r)
        v = sum((x - m) ** 2 for x in r) / len(r)
        return math.sqrt(v) if v > 0 else 0.0

    @staticmethod
    def _norm_cdf(x):
        return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))

    def _bsm_call(self, S, K, T, r, sigma):
        if T <= 0 or sigma <= 0 or S <= 0:
            return max(0, S - K)
        d1 = (math.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * math.sqrt(T))
        d2 = d1 - sigma * math.sqrt(T)
        return S * self._norm_cdf(d1) - K * math.exp(-r * T) * self._norm_cdf(d2)

    def _implied_vol(self, mp, S, K, T, r=0.0):
        if T <= 0 or S <= 0 or mp <= 0:
            return 0.0
        lo, hi = 0.001, 5.0
        for _ in range(50):
            mid_v = (lo + hi) / 2
            if self._bsm_call(S, K, T, r, mid_v) < mp:
                lo = mid_v
            else:
                hi = mid_v
        return (lo + hi) / 2

    def _is_toxic(self, product):
        p = PARAMS
        if not p.get("toxic_flow_enabled", 0):
            return False
        fc = self.fill_counts.get(product, {"bid": 0, "ask": 0})
        total = fc["bid"] + fc["ask"]
        if total < 20:
            return False
        return max(fc["bid"], fc["ask"]) / total > p.get("toxic_threshold", 0.7)

    def _check_cb(self, product):
        p = PARAMS
        if self.tick < self.cb_disabled_until.get(product, 0):
            return True
        cum = self.strategy_pnl.get(product, 0.0)
        if cum < p.get("cb_loss_limit", -200):
            self.cb_disabled_until[product] = self.tick + int(p.get("cb_cooldown_ticks", 50))
            self.strategy_pnl[product] = 0.0
            return True
        return False

    def _update_lead_lag(self):
        p = PARAMS
        if not p.get("lead_lag_enabled", 0):
            return
        window = int(p.get("lead_lag_window", 50))
        kp = self.prices.get("KELP", [])
        sp = self.prices.get("SQUID_INK", [])
        if len(kp) < window + 5 or len(sp) < window + 5:
            return
        k = kp[-(window+1):-1]
        s = sp[-window:]
        kr = [k[i+1] - k[i] for i in range(len(k)-1)]
        sr = [s[i+1] - s[i] for i in range(len(s)-1)]
        if len(kr) != len(sr) or len(kr) < 10:
            return
        n = len(kr)
        mk, ms = sum(kr)/n, sum(sr)/n
        cov = sum((kr[i]-mk)*(sr[i]-ms) for i in range(n))/n
        sk = math.sqrt(sum((x-mk)**2 for x in kr)/n)
        ss = math.sqrt(sum((x-ms)**2 for x in sr)/n)
        if sk > 0 and ss > 0:
            self.lead_lag_cache["kelp_leads_squid"] = cov / (sk * ss)
        s2 = sp[-(window+1):-1]
        k2 = kp[-window:]
        s2r = [s2[i+1]-s2[i] for i in range(len(s2)-1)]
        k2r = [k2[i+1]-k2[i] for i in range(len(k2)-1)]
        if len(s2r) == len(k2r) and len(s2r) >= 10:
            n2 = len(s2r)
            ms2, mk2 = sum(s2r)/n2, sum(k2r)/n2
            cov2 = sum((s2r[i]-ms2)*(k2r[i]-mk2) for i in range(n2))/n2
            ss2 = math.sqrt(sum((x-ms2)**2 for x in s2r)/n2)
            sk2 = math.sqrt(sum((x-mk2)**2 for x in k2r)/n2)
            if ss2 > 0 and sk2 > 0:
                self.lead_lag_cache["squid_leads_kelp"] = cov2 / (ss2 * sk2)

    def run(self, state: TradingState) -> Tuple[Dict[str, List[Order]], int, str]:
        self.tick += 1
        p = PARAMS
        orders = {}
        conversions = 0

        warmup = p.get("warmup_ticks", 5)
        liq_start = p.get("liquidation_start", 900)
        close_start = p.get("close_start", 960)

        if self.tick <= warmup:
            size_mult = 0.0
        elif self.tick <= 100:
            size_mult = p.get("size_mult_small", 0.25)
        elif self.tick <= 200:
            size_mult = p.get("size_mult_half", 0.5)
        elif self.tick <= liq_start:
            size_mult = 1.0
        elif self.tick <= close_start:
            size_mult = 0.3
        else:
            size_mult = 0.0

        for product, trades in state.own_trades.items():
            for trade in trades:
                fc = self.fill_counts.setdefault(product, {"bid": 0, "ask": 0})
                if trade.buyer == "SUBMISSION":
                    self.strategy_pnl[product] = self.strategy_pnl.get(product, 0.0) - trade.quantity * trade.price
                    fc["bid"] += 1
                elif trade.seller == "SUBMISSION":
                    self.strategy_pnl[product] = self.strategy_pnl.get(product, 0.0) + trade.quantity * trade.price
                    fc["ask"] += 1

        if self.tick % 500 == 0:
            self.fill_counts.clear()
        if p.get("lead_lag_enabled", 0) and self.tick % 50 == 0:
            self._update_lead_lag()

        use_kalman = p.get("use_kalman_fv", 0)
        obi_enabled = p.get("obi_enabled", 0)
        obi_weight = p.get("obi_weight", 0.5)
        multi_level = p.get("multi_level", 1)
        ml_decay = p.get("multi_level_decay", 0.5)
        vol_adapt = p.get("vol_adapt_enabled", 0)
        vol_scale = p.get("vol_adapt_scale", 1.0)
        vol_window = int(p.get("vol_adapt_window", 50))
        penny_jump = p.get("penny_jump_enabled", 0)
        adverse_limit = int(p.get("adverse_vol_limit", 15))

        for product, od in state.order_depths.items():
            position = state.position.get(product, 0)
            limit = POSITION_LIMITS.get(product, 50)
            prod_orders = []

            if not od.buy_orders or not od.sell_orders:
                orders[product] = []
                continue

            best_bid = max(od.buy_orders.keys())
            best_ask = min(od.sell_orders.keys())
            mid = (best_bid + best_ask) / 2.0

            prev_mid = self.prices.get(product, [mid])[-1]
            self.prices.setdefault(product, []).append(mid)
            if len(self.prices[product]) > 500:
                self.prices[product] = self.prices[product][-500:]
            if prev_mid != 0:
                ret = (mid - prev_mid) / prev_mid
                self.returns.setdefault(product, []).append(ret)
                if len(self.returns[product]) > 500:
                    self.returns[product] = self.returns[product][-500:]

            kf_fv = self._kalman_update(product, mid)
            obi_val = self._obi(od) if obi_enabled else 0.0
            rvol = self._realized_vol(product, vol_window) if vol_adapt else 0.0

            if self.tick > close_start:
                if position > 0:
                    prod_orders.append(Order(product, best_bid, -position))
                elif position < 0:
                    prod_orders.append(Order(product, best_ask, -position))
                orders[product] = prod_orders
                continue

            if self.tick > liq_start and abs(position) > 0:
                rq = max(1, abs(position) // 5)
                if position > 0:
                    prod_orders.append(Order(product, best_bid, -rq))
                else:
                    prod_orders.append(Order(product, best_ask, rq))
                orders[product] = prod_orders
                continue

            if size_mult <= 0:
                orders[product] = []
                continue

            if self._check_cb(product):
                orders[product] = []
                continue
            if self._is_toxic(product):
                orders[product] = []
                continue

            # ── STABLE: RAINFOREST_RESIN ──
            if product in STABLE_PRODUCTS:
                fv = STABLE_PRODUCTS[product]
                spread = p.get("resin_spread", 2)
                qty = max(1, int(p.get("resin_order_qty", 10) * size_mult))
                skew = p.get("resin_skew_factor", 0.5)
                soft_frac = p.get("resin_soft_frac", 0.8)

                if obi_enabled:
                    fv += obi_val * obi_weight
                fv_adj = fv + (-position * skew)

                if abs(position) > limit * soft_frac:
                    spread += 1 + int((abs(position) / limit - soft_frac) * 5)
                if vol_adapt and rvol > 0:
                    spread = max(1, int(spread * (1 + rvol * vol_scale * 100)))

                bp = int(fv_adj - spread)
                ap = int(fv_adj + spread)

                if penny_jump or p.get("resin_penny_jump", 0):
                    if bp < best_bid:
                        bp = best_bid + 1
                    if ap > best_ask:
                        ap = best_ask - 1

                if p.get("take_enabled", 1):
                    edge = p.get("take_edge_min", 1.0)
                    for price in sorted(od.sell_orders.keys()):
                        if price < fv - edge:
                            vol = min(abs(od.sell_orders[price]), adverse_limit)
                            tq = min(vol, limit - position)
                            if tq > 0:
                                prod_orders.append(Order(product, price, tq))
                                position += tq
                    for price in sorted(od.buy_orders.keys(), reverse=True):
                        if price > fv + edge:
                            vol = min(od.buy_orders[price], adverse_limit)
                            tq = min(vol, limit + position)
                            if tq > 0:
                                prod_orders.append(Order(product, price, -tq))
                                position -= tq

                for level in range(multi_level):
                    lq = max(1, int(qty * (ml_decay ** level)))
                    ls = spread + level
                    bq = min(lq, limit - position)
                    aq = min(lq, limit + position)
                    if bq > 0:
                        prod_orders.append(Order(product, int(fv_adj - ls), bq))
                        position += bq
                    if aq > 0:
                        prod_orders.append(Order(product, int(fv_adj + ls), -aq))
                        position -= aq

            # ── VOLATILE: KELP, SQUID_INK ──
            elif product in VOLATILE_PRODUCTS:
                prefix = "kelp_" if product == "KELP" else "squid_"
                alpha = p.get(f"{prefix}ema_alpha", 0.3)
                spread = p.get(f"{prefix}spread", 3)
                qty = max(1, int(p.get(f"{prefix}order_qty", 5) * size_mult))
                skew = p.get(f"{prefix}skew_factor", 0.5)
                soft_frac = p.get(f"{prefix}soft_frac", 0.75)

                prev_ema = self.emas.get(product, mid)
                ema = alpha * mid + (1 - alpha) * prev_ema
                self.emas[product] = ema

                fv = kf_fv if use_kalman else ema
                if obi_enabled:
                    fv += obi_val * obi_weight

                if p.get("lead_lag_enabled", 0):
                    if product == "SQUID_INK":
                        corr = self.lead_lag_cache.get("kelp_leads_squid", 0)
                        if abs(corr) > 0.1 and len(self.prices.get("KELP", [])) >= 2:
                            fv += corr * (self.prices["KELP"][-1] - self.prices["KELP"][-2]) * 0.3
                    elif product == "KELP":
                        corr = self.lead_lag_cache.get("squid_leads_kelp", 0)
                        if abs(corr) > 0.1 and len(self.prices.get("SQUID_INK", [])) >= 2:
                            fv += corr * (self.prices["SQUID_INK"][-1] - self.prices["SQUID_INK"][-2]) * 0.3

                fv_adj = fv + (-position * skew)

                if abs(position) > limit * soft_frac:
                    spread += 1 + int((abs(position) / limit - soft_frac) * 5)
                if vol_adapt and rvol > 0:
                    spread = max(1, int(spread * (1 + rvol * vol_scale * 100)))

                if penny_jump and best_ask - best_bid > 2:
                    pass  # Let multi-level handle it

                if p.get("take_enabled", 1):
                    edge = p.get("take_edge_min", 1.0)
                    for price in sorted(od.sell_orders.keys()):
                        if price < fv - edge:
                            vol = min(abs(od.sell_orders[price]), adverse_limit)
                            tq = min(vol, limit - position)
                            if tq > 0:
                                prod_orders.append(Order(product, price, tq))
                                position += tq
                    for price in sorted(od.buy_orders.keys(), reverse=True):
                        if price > fv + edge:
                            vol = min(od.buy_orders[price], adverse_limit)
                            tq = min(vol, limit + position)
                            if tq > 0:
                                prod_orders.append(Order(product, price, -tq))
                                position -= tq

                for level in range(multi_level):
                    lq = max(1, int(qty * (ml_decay ** level)))
                    ls = spread + level
                    bq = min(lq, limit - position)
                    aq = min(lq, limit + position)
                    if bq > 0:
                        prod_orders.append(Order(product, int(fv_adj - ls), bq))
                        position += bq
                    if aq > 0:
                        prod_orders.append(Order(product, int(fv_adj + ls), -aq))
                        position -= aq

                if p.get("trend_enabled", 0) and len(self.prices[product]) >= 30:
                    rmean = sum(self.prices[product][-30:]) / 30
                    threshold = p.get("trend_threshold", 0.003)
                    tq = max(1, int(p.get("trend_qty", 3) * size_mult))
                    if ema > rmean * (1 + threshold):
                        q = min(tq, limit - position)
                        if q > 0:
                            prod_orders.append(Order(product, best_ask, q))
                    elif ema < rmean * (1 - threshold):
                        q = min(tq, limit + position)
                        if q > 0:
                            prod_orders.append(Order(product, best_bid, -q))

            # ── BASKET ──
            elif product in BASKET_PRODUCTS:
                weights = BASKET_PRODUCTS[product]
                z_enter = p.get("basket_z_enter", 1.5)
                z_exit = p.get("basket_z_exit", 0.5)
                window = p.get("basket_window", 100)
                bkt_qty = max(1, int(p.get("basket_order_qty", 2) * size_mult))
                component_val = 0
                ok = True
                for comp, w in weights.items():
                    if comp not in state.order_depths:
                        ok = False
                        break
                    cod = state.order_depths[comp]
                    if not cod.buy_orders or not cod.sell_orders:
                        ok = False
                        break
                    component_val += w * (max(cod.buy_orders.keys()) + min(cod.sell_orders.keys())) / 2
                if ok and component_val > 0:
                    sv = mid - component_val
                    hist = self.spread_history.setdefault(product, [])
                    hist.append(sv)
                    if len(hist) > 500:
                        self.spread_history[product] = hist[-500:]
                    if len(hist) >= max(30, window // 3):
                        recent = hist[-window:] if len(hist) >= window else hist
                        ms = sum(recent) / len(recent)
                        ss = math.sqrt(sum((x - ms)**2 for x in recent) / len(recent))
                        if ss > 0.5:
                            z = (sv - ms) / ss
                            if z > z_enter:
                                sq = min(bkt_qty, limit + position)
                                if sq > 0:
                                    prod_orders.append(Order(product, int(mid - 1), -sq))
                            elif z < -z_enter:
                                bq = min(bkt_qty, limit - position)
                                if bq > 0:
                                    prod_orders.append(Order(product, int(mid + 1), bq))
                            elif abs(z) < z_exit and abs(position) > 0:
                                if position > 0:
                                    prod_orders.append(Order(product, int(mid - 1), -min(bkt_qty, position)))
                                elif position < 0:
                                    prod_orders.append(Order(product, int(mid + 1), min(bkt_qty, -position)))

            # ── CONVERSION (MACARONS) ──
            elif product == "MAGNIFICENT_MACARONS":
                obs = state.observations
                if obs and obs.conversionObservations:
                    conv = obs.conversionObservations.get("MAGNIFICENT_MACARONS")
                    if conv:
                        sb, sa = conv.bidPrice, conv.askPrice
                        tf, et, it = conv.transportFees, conv.exportTariff, conv.importTariff
                        if sb - best_ask - tf - et > 1:
                            cq = min(10, limit - position)
                            if cq > 0:
                                prod_orders.append(Order(product, best_ask, cq))
                                conversions = -cq
                        if best_bid - sa - tf - it > 1:
                            cq = min(10, limit + position)
                            if cq > 0:
                                prod_orders.append(Order(product, best_bid, -cq))
                                conversions = cq

            # ── OPTIONS (VOUCHERS) — BSM IV ──
            elif product in VOUCHER_STRIKES:
                K = VOUCHER_STRIKES[product]
                bsm_on = p.get("bsm_enabled", 0)
                bsm_window = int(p.get("bsm_vol_window", 50))
                bsm_z = p.get("bsm_z_enter", 2.0)
                opt_qty = max(1, int(p.get("bsm_qty", 3) * size_mult))
                rock_od = state.order_depths.get("VOLCANIC_ROCK")
                S = None
                if rock_od and rock_od.buy_orders and rock_od.sell_orders:
                    S = (max(rock_od.buy_orders.keys()) + min(rock_od.sell_orders.keys())) / 2.0
                if bsm_on and S and S > 0:
                    T = max(0.001, (TICKS_PER_DAY - self.tick) / TICKS_PER_DAY * (1/252))
                    iv = self._implied_vol(mid, S, K, T)
                    if iv > 0:
                        ivh = self.iv_history.setdefault(product, [])
                        ivh.append(iv)
                        if len(ivh) > 500:
                            self.iv_history[product] = ivh[-500:]
                        if len(ivh) >= bsm_window:
                            ri = ivh[-bsm_window:]
                            mi = sum(ri) / len(ri)
                            si = math.sqrt(sum((x-mi)**2 for x in ri) / len(ri))
                            if si > 0.001:
                                z = (iv - mi) / si
                                if z < -bsm_z:
                                    bq = min(opt_qty, limit - position)
                                    if bq > 0:
                                        prod_orders.append(Order(product, int(mid + 1), bq))
                                elif z > bsm_z:
                                    sq = min(opt_qty, limit + position)
                                    if sq > 0:
                                        prod_orders.append(Order(product, int(mid - 1), -sq))
                else:
                    pb = self.prices.get(product, [])
                    if len(pb) >= 50:
                        mp = sum(pb[-50:]) / 50
                        sp = math.sqrt(sum((x-mp)**2 for x in pb[-50:]) / 50)
                        if sp > 0.5:
                            z = (mid - mp) / sp
                            oq = max(1, int(3 * size_mult))
                            if z < -2.0:
                                bq = min(oq, limit - position)
                                if bq > 0:
                                    prod_orders.append(Order(product, int(mid + 1), bq))
                            elif z > 2.0:
                                sq = min(oq, limit + position)
                                if sq > 0:
                                    prod_orders.append(Order(product, int(mid - 1), -sq))

            # ── DEFAULT MM ──
            else:
                prev_ema = self.emas.get(product, mid)
                ema = 0.3 * mid + 0.7 * prev_ema
                self.emas[product] = ema
                q = max(1, int(5 * size_mult))
                bq = min(q, limit - position)
                aq = min(q, limit + position)
                if bq > 0:
                    prod_orders.append(Order(product, int(ema - 3), bq))
                if aq > 0:
                    prod_orders.append(Order(product, int(ema + 3), -aq))

            orders[product] = prod_orders

        # ── Pairs Trading ──
        if p.get("pairs_enabled", 0) and size_mult > 0:
            kod = state.order_depths.get("KELP")
            sod = state.order_depths.get("SQUID_INK")
            if (kod and sod and kod.buy_orders and kod.sell_orders and
                sod.buy_orders and sod.sell_orders):
                km = (max(kod.buy_orders.keys()) + min(kod.sell_orders.keys())) / 2.0
                sm = (max(sod.buy_orders.keys()) + min(sod.sell_orders.keys())) / 2.0
                ps = km - sm
                ph = self.spread_history.setdefault("_pairs_ks", [])
                ph.append(ps)
                if len(ph) > 500:
                    self.spread_history["_pairs_ks"] = ph[-500:]
                w = int(p.get("pairs_window", 60))
                if len(ph) >= max(30, w // 3):
                    r = ph[-w:] if len(ph) >= w else ph
                    ms = sum(r) / len(r)
                    ss = math.sqrt(sum((x-ms)**2 for x in r) / len(r))
                    if ss > 0.5:
                        z = (ps - ms) / ss
                        ze = p.get("pairs_z_enter", 2.0)
                        zx = p.get("pairs_z_exit", 0.5)
                        pq = max(1, int(p.get("pairs_qty", 3) * size_mult))
                        kp = state.position.get("KELP", 0)
                        sp = state.position.get("SQUID_INK", 0)
                        kl, sl = POSITION_LIMITS.get("KELP", 50), POSITION_LIMITS.get("SQUID_INK", 50)
                        if z > ze:
                            sq = min(pq, kl + kp)
                            bq = min(pq, sl - sp)
                            if sq > 0:
                                orders.setdefault("KELP", []).append(Order("KELP", int(km-1), -sq))
                            if bq > 0:
                                orders.setdefault("SQUID_INK", []).append(Order("SQUID_INK", int(sm+1), bq))
                        elif z < -ze:
                            bq = min(pq, kl - kp)
                            sq = min(pq, sl + sp)
                            if bq > 0:
                                orders.setdefault("KELP", []).append(Order("KELP", int(km+1), bq))
                            if sq > 0:
                                orders.setdefault("SQUID_INK", []).append(Order("SQUID_INK", int(sm-1), -sq))
                        elif abs(z) < zx:
                            if kp > 0:
                                orders.setdefault("KELP", []).append(Order("KELP", int(km-1), -min(pq, kp)))
                            elif kp < 0:
                                orders.setdefault("KELP", []).append(Order("KELP", int(km+1), min(pq, -kp)))
                            if sp > 0:
                                orders.setdefault("SQUID_INK", []).append(Order("SQUID_INK", int(sm-1), -min(pq, sp)))
                            elif sp < 0:
                                orders.setdefault("SQUID_INK", []).append(Order("SQUID_INK", int(sm+1), min(pq, -sp)))

        return orders, conversions, ""
